### ISSUE TITLE
l10n: Fix text string

### ISSUE THREAD

**Issue by Valdnet** [datenangebot/health#81]
After many text string repairs:

https://github.com/datenangebot/health/blob/26159dfaecea93b46f646d51a472f388574c6c21/src/modules/activities/ActivitiesChart.vue#L236

still available in Transefix as:

![obraz](https://user-images.githubusercontent.com/47037905/116522713-ca45bb00-a8d5-11eb-9a29-00d9d4a93792.png)

The text string should be corrected so that only Transifex appears: `Distance`.

**Comment by rakekniven** [comment]
Better add value for distance as placeholder to the string. Works for all languages.

**Comment by Valdnet** [comment]
Strange, previously the change was scanned by nextcloud-bot as:

![obraz](https://user-images.githubusercontent.com/47037905/116662505-21ab6000-a996-11eb-8bf6-c18ca936032c.png)

And now, without making any changes, it is:

![obraz](https://user-images.githubusercontent.com/47037905/116662266-d8f3a700-a995-11eb-9ab2-71942fd48374.png)

@rakekniven I think it can stay that way 😉.

**Comment by rakekniven** [comment]
Ok, so you can close this issue.
